name: Smoke test post deploy
description: Invoke a script that visits a deploy smoke check page that displays whether the backend / db are healthy.
inputs:
  deploy-env:
    description: The environment being deployed (e.g. "prod" or "test")
    required: true
runs:
  using: composite
  steps:
    - name: create env file
      shell: bash
      working-directory: frontend
      run: |
        touch .env
        echo REACT_APP_BASE_URL=https://${{ inputs.deploy-env }}.simplereport.gov >> .env.production.local
    - name: Run smoke test script
      shell: bash
      working-directory: frontend
      run: yarn smoke:deploy:ci