name: Smoke test post deploy
description: Ping a backend health endpoint that reaches into the db and return a status message to a frontend status page. Visit that page and ensure things are healthy
inputs:
  deploy-env:
    description: The environment being deployed (e.g. "prod" or "test")
    required: true
runs:
  using: composite
  steps:
    - name: create env file
      shell: bash
      working-directory: frontend
      run: |
        touch .env
        echo REACT_APP_BASE_URL=https://${{ inputs.deploy-env }}.simplereport.gov/ >> .env.production.local
    - name: Run smoke test script
      shell: bash
      working-directory: frontend
      run: yarn smoke:env:deploy:ci