name: Terraform Action wait for slot commit
description: Build and push Docker image to the registry
inputs:
  deploy_env:
    description: The environment to deploy to
    required: true

runs:
  using: composite
  steps:
    - name: Wait for correct commit to be deployed in staging slot
      shell: bash
      run: make wait-for-${{ inputs.deploy_env }}-slot-commit