version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "docker"
    directory: "/backend"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "docker"
    directory: "/backend/db-setup"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "docker"
    directory: "/cypress"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "docker"
    directory: "/frontend"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "docker"
    directory: "/nginx"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "docker"
    directory: "/ops/services/container_instances/db_client/image"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "gradle"
    directory: "/backend"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "npm"
    directory: "/frontend"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      eslint:
        patterns:
        - "eslint*"
      graphql:
        patterns:
        - "@graphql*"
      jest:
        patterns:
        - "jest*"
      storybook:
        patterns:
        - "@storybook*"
        - "storybook*"
        - "msw-storybook-addon"
      types:
        patterns:
        - "@types/*"
      typescript-eslint:
        patterns:
        - "@typescript-eslint*"

  - package-ecosystem: "npm"
    directory: "/cypress"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "npm"
    directory: "/ops/services/app_functions/report_stream_batched_publisher/functions"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "terraform"
    directory: "/ops/global"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "terraform"
    directory: "/ops/services/okta-global"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "terraform"
    directory: "/ops/test"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "terraform"
    directory: "/ops/test/persistent"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"