# Issue to track batching updates feature: https://github.com/github/roadmap/issues/148

version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "docker"
    directory: "/backend/db-setup"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "docker"
    directory: "/cypress"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "docker"
    directory: "/ops/services/container_instances/db_client/image"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "github-actions"
    # this checks the .github/workflows directory by default
    # any other directory for github-actions seems broken at the moment
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"
      
  - package-ecosystem: "npm"
    directory: "/frontend"
    open-pull-requests-limit: 40
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"
      
  - package-ecosystem: "npm"
    directory: "/cypress"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "npm"
    directory: "/ops/services/app_functions/report_stream_batched_publisher/functions"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "terraform"
    directory: "/ops/global"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "terraform"
    directory: "/ops/services/okta-global"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "terraform"
    directory: "/ops/test"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"

  - package-ecosystem: "terraform"
    directory: "/ops/test/persistent"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "alismx"
