ARG NODE_VER
ARG NODE_ENV

FROM node:${NODE_VER}-alpine
ENV NODE_ENV=${NODE_ENV}

RUN apk add --no-cache git

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

WORKDIR /frontend
CMD ["yarn", "soft-start"]

EXPOSE 3000
