# Dockerfile for local development
FROM node:14-alpine

RUN apk add g++ make python

# create directory on container
WORKDIR /frontend/app 

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /frontend/app

RUN yarn

COPY . /frontend/app

CMD ["yarn", "start"]
