services:
  backend:
    environment:
      SPRING_PROFILES_ACTIVE: dev,db-dockerized
      SPRING_LIQUIBASE_ENABLED: "true"
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
  frontend:
    image: ghcr.io/cdcgov/prime-simplereport/frontend-lighthouse:${DOCKER_FRONTEND_LIGHTHOUSE_IMAGE_VERSION:-latest}
  mailhog:
    profiles:
      - donotstart