services:
  # Postgresql database
  db:
    build:
      context: backend/db-setup
    container_name: "${DB_NAME:-db}"
    environment:
      POSTGRES_PASSWORD: admin_password_for_local_dev_is_not_very_secure
      SNAPSHOT: /usr/local/lib/anon_dump.sql
    volumes:
      # Create/use a named volume so that the database is not wiped if we recreate the container
      - db-data:/var/lib/postgresql/data
      # Mount init scripts for first-run user/schema creation
      - ./backend/db-setup/create-db.sh:/docker-entrypoint-initdb.d/01-user-db-creation.sh
      - ./backend/db-setup/create-metabase-db.sh:/docker-entrypoint-initdb.d/02-metabase-db-creation.sh
      - ./backend/db-setup/reset-db.sql:/usr/local/lib/reset-db.sql
      - ./backend/db-setup/anonymize-detect.sh:/usr/local/lib/anonymize-detect.sh
      - ./backend/db-setup/remove-anon.sh:/usr/local/lib/remove-anon.sh
      - ./backend/db-setup/anonymize-db.sql:/usr/local/lib/anonymize-db.sql
      - ./backend/db-setup/reset-metabase-db.sql:/usr/local/lib/reset-metabase-db.sql
      - ./backend/db-setup/restore-db.sh:/usr/local/lib/restore-db.sh
      - ./backend/db-setup/nuke-db.sh:/usr/local/lib/nuke-db.sh
      - ./backend/db-setup/snapshot-db.sh:/usr/local/lib/snapshot-db.sh
      - ./backend/db-setup/.pgpass/:/usr/local/lib/.pgpass
      - ./backend/db-setup/snapshots/:/usr/local/lib/snapshots/
      - ./backend/db-setup/generate_db_data.py:/usr/local/lib/generate_db_data.py
    command: -p ${SR_DB_PORT:-5432} -c log_statement=all
    expose:
      - "${SR_DB_PORT:-5432}"
    ports:
      - "${SR_DB_PORT:-5432}:${SR_DB_PORT:-5432}"
  # Spring Boot backend
  backend:
    build:
      context: backend
    image: ghcr.io/cdcgov/prime-simplereport/backend:latest
    container_name: backend
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: okta-local,db-dockerized,create-sample-data
      SPRING_LIQUIBASE_ENABLED: "true"
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    volumes:
      - ./.git:/app/.git
      - ./backend:/app/backend/
    depends_on:
      - db
    expose:
      - "8080"
  # React frontend
  frontend:
    build:
      context: frontend
    image: ghcr.io/cdcgov/prime-simplereport/frontend:latest
    container_name: frontend
    environment:
      REACT_APP_BASE_URL: https://localhost.simplereport.gov
      REACT_APP_BACKEND_URL: https://localhost.simplereport.gov/api
      PUBLIC_URL: /app/
      REACT_APP_OKTA_ENABLED: "true"
      REACT_APP_DISABLE_MAINTENANCE_BANNER: "true"
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    volumes:
      - ./.git:/app/.git
      - ./frontend:/app/frontend/
      - node_modules:/app/frontend/node_modules
      - ./backend/src/main/resources/graphql:/app/backend/src/main/resources/graphql
    expose:
      - "3000"
  # This is an nginx server that serves both the frontend and the backend
  # at https://localhost.simplereport.gov, using certs generated by mkcert
  nginx:
    build:
      context: nginx
    image: ghcr.io/cdcgov/prime-simplereport/nginx:latest
    container_name: nginx
    depends_on:
      - backend
      - frontend
    volumes:
      - ./certs:/etc/nginx/certs
      - ./frontend/public/index.html:/etc/nginx/html/index.html
    ports:
      - "80:80"
      - "443:443"
  mailhog:
    ports:
      - '1025:1025'
      - '8025:8025'
    image: mailhog/mailhog
    
volumes:
  db-data:
  node_modules:
