services:
  backend:
    environment:
      SPRING_PROFILES_ACTIVE: dev,db-dockerized
      SPRING_LIQUIBASE_ENABLED: "true"
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
  frontend:
    environment:
      VITE_BASE_URL: https://localhost.simplereport.gov
      VITE_BACKEND_URL: https://localhost.simplereport.gov/api
      PUBLIC_URL: /app/
      VITE_OKTA_ENABLED: "false"
      VITE_DISABLE_MAINTENANCE_BANNER: "true"
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    command: ["./ci-git-fix.sh"]
  nginx:
    hostname: localhost.simplereport.gov
  mailhog:
    profiles:
      - donotstart