name: Build ReportStream reporting functions
description: Build the ReportStream uploader and exception handler functions
inputs:
  deploy-env:
    description: The environment being deployed (e.g. "prod" or "test")
    required: true
runs:
  using: composite
  steps:
    - name: Build function source bundle
      shell: bash
      working-directory: ./ops/services/app_functions/report_stream_batched_publisher/functions
      run: |
        echo "::group::Build function"
        yarn build:production
