//Icon Imports
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowRight,
  faBook,
  faComments,
  faDatabase,
  faEnvelope,
  faExclamationTriangle,
  faExternalLinkAlt,
  faFileWord,
  faHandPaper,
  faPlus,
  faQuestionCircle,
  faSync,
  faTimes,
  faTrash,
  faUser,
  faSearch,
  faArrowLeft,
  faTimesCircle,
  faCircle,
  faCog,
  faEdit,
  faSave,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faArrowRight,
  faBook,
  faComments,
  faDatabase,
  faEnvelope,
  faExclamationTriangle,
  faExternalLinkAlt,
  faFileWord,
  faHandPaper,
  faPlus,
  faQuestionCircle,
  faSync,
  faTimes,
  faTrash,
  faUser,
  faSearch,
  faArrowLeft,
  faTimesCircle,
  faCircle,
  faCog,
  faEdit,
  faSave
);
