name: Maintenance banner status change notification
description: Sends an email to the support team when the state of the maintenance banner changes in PROD
inputs:
  status-active:
    description: boolean that represents if the banner is active (on) or inactive (off)
    required: true
    default: true
runs:
  uses: composite
  steps:
    - id: generate-subject
      shell: bash
      run: |
        if [[ "true" == "${{ inputs.status-active }}" ]]
                    then echo "email-subject='Simple Report maintenance banner is ON'" >> $GITHUB_OUTPUT
                    else echo "email-subject='Simple Report maintenance banner is OFF'" >> $GITHUB_OUTPUT
        fi
    - id: generate-body
      shell: bash
      run: |
        if [[ "true" == "${{ inputs.status-active }}" ]]
                 then echo "email-body='The maintenance banner is now being displayed in the Simple Report application.'" >> $GITHUB_OUTPUT
                 else echo "email-body='The maintenance banner has been removed from the Simple Report application.'" >> $GITHUB_OUTPUT
        fi
    - name: send email to support team
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_USER }}
        password: ${{ secrets.GMAIL_PASS }}
        subject: ${{ steps.generate-subject.outputs.email-subject }}
        body: ${{ steps.generate-body.outputs.email-body }}
        to: ${{ secrets.SUPPORT_MAIL_ADDRESS }}
        from: ${{ secrets.APP_GMAIL_ADDRESS }}
    - name: notify banner is ON
      uses: dawidd6/action-send-mail@v3
      if: ${{ inputs.status-active == true }}
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_USER }}
        password: ${{ secrets.GMAIL_PASS }}
        subject: Simple Report maintenance banner is ON
        body: The maintenance banner is now being displayed in the Simple Report application.
        to: ${{ secrets.SUPPORT_MAIL_ADDRESS }}
        from: ${{ secrets.APP_GMAIL_ADDRESS }}
    - name: notify banner is OFF
      uses: dawidd6/action-send-mail@v3
      if: ${{ inputs.status-active == false }}
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_USER }}
        password: ${{ secrets.GMAIL_PASS }}
        subject: Simple Report maintenance banner is OFF
        body: The maintenance banner has been removed from the Simple Report application.
        to: ${{ secrets.SUPPORT_MAIL_ADDRESS }}
        from: ${{ secrets.APP_GMAIL_ADDRESS }}