name: Build Database Client Container
description: Build and push the db-client container image needed for database access.
runs:
  using: composite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ops/services/container_instances/db_client/image
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ACR
        run: docker login ${{ secrets.ACR_REPO_URL }} -u ${{ secrets.ACR_ADMIN_USERNAME }} -p ${{ secrets.ACR_ADMIN_PASWORD }}
      - name: Build and push Docker images
        run: ./build_and_push.sh 
