name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Does this issue have a priority label?
    description: |
      Options:
        P0 - Highest prioirty, all other work stops, major functionality is broken
        P1 - High Priority, this should be done before other work
        P2 - Ordinary flow of work
        P3 - Nice to have
        P4 - Informational
    options:
    - label: I have added a priority label
      required: true
- type: checkboxes
  attributes:
    label: Has issue been assigned to a team?
    description: |
      Options:
        Growth & Engagement
        Better Data
        Design
    options:
    - label: I have added a team label
      required: true