name: Terraform Action Deployment
description: Build and push Docker image to the registry
inputs:
  azure_creds:
    description: Azure credentials
    required: true
  deploy_env:
    description: The environment to deploy to
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_creds }}
    - uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.3.3
    - name: Build ReportStream function app
      uses: ./.github/actions/build-reportstream-functions
      with:
        deploy-env: ${{ inputs.deploy_env }}
    - name: Terraform Init
      shell: bash
      run: make init-${{ inputs.deploy_env }}
    - name: Terraform deploy (infrastructure and staging slot)
      shell: bash
      run: make deploy-${{ inputs.deploy_env }}