export const PATIENT_TERM = "person";
export const PATIENT_TERM_CAP = "Person";
export const PATIENT_TERM_PLURAL = "people";
export const PATIENT_TERM_PLURAL_CAP = "People";

// NOTE: Any time SimpleReport goes live in a new state, this file must be updated.
// Otherwise, organizations will not be able to create facilities in the new state.
export const liveJurisdictions = [
  "AZ",
  "CA",
  "CO",
  "FL",
  "GU",
  "LA",
  "MS",
  "MT",
  "ND",
  "NM",
  "OH",
  "PA",
  "TX",
  "VT",
];

export const states = {
  AK: "Alaska",
  AL: "Alabama",
  AR: "Arkansas",
  AS: "American Samoa",
  AZ: "Arizona",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DC: "Washington, D.C.",
  DE: "Delaware",
  FL: "Florida",
  FM: "Micronesia",
  GA: "Georgia",
  GU: "Guam",
  HI: "Hawaii",
  IA: "Iowa",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  MA: "Massachusetts",
  MD: "Maryland",
  ME: "Maine",
  MH: "Marshall Islands",
  MI: "Michigan",
  MN: "Minnesota",
  MO: "Montana",
  MP: "Mariana Islands",
  MS: "Mississippi",
  MT: "Montana",
  NC: "North Carolina",
  ND: "North Dakota",
  NE: "Nebraska",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NV: "Nevada",
  NY: "New York",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  PR: "Puerto Rico",
  PW: "Palau",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VA: "Virginia",
  VI: "U.S. Virgin Islands",
  VT: "Vermont",
  WA: "Washington",
  WI: "Wisconsin",
  WV: "West Virginia",
  WY: "Wyoming",
};

export const stateCodes = Object.keys(states);

export const languages: Language[] = [
  "English",
  "Spanish",
  "Unknown",
  "Afrikaans",
  "Amaric",
  "American Sign Language",
  "Arabic",
  "Armenian",
  "Aromanian; Arumanian; Macedo-Romanian",
  "Bantu (other)",
  "Bengali",
  "Braile",
  "Burmese",
  "Cambodian",
  "Cantonese",
  "Caucasian (other)",
  "Chaochow",
  "Cherokee",
  "Chinese",
  "Creoles and pidgins, French-based (Other)",
  "Cushitic (other)",
  "Dakota",
  "Farsi",
  "Fiji",
  "Filipino; Pilipino",
  "French",
  "German",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Hmong",
  "Indonesian",
  "Italian",
  "Japanese",
  "Kannada",
  "Korean",
  "Kru languages",
  "Kurdish",
  "Laotian",
  "Latin",
  "Luganda",
  "Malayalam",
  "Mandar",
  "Mandarin",
  "Marathi",
  "Marshallese",
  "Mien",
  "Mixteca",
  "Mon-Khmer (Other)",
  "Mongolian",
  "Morrocan Arabic",
  "Navajo",
  "Nepali",
  "Not Specified",
  "Oaxacan",
  "Other",
  "Pashto",
  "Portuguese",
  "Punjabi",
  "Rarotongan; Cook Islands Maori",
  "Russian",
  "Samoan",
  "Sebuano",
  "Serbo Croatian",
  "Sign Languages",
  "Singhalese",
  "Somali",
  "Swahili",
  "Syrian",
  "Tagalog",
  "Tahitian",
  "Taiwanese",
  "Tamil",
  "Tegulu",
  "Thai",
  "Tigrinya",
  "Triqui",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
  "Yiddish",
  "Zapotec",
];

export const urls = {
  FACILITY_INFO:
    process.env.REACT_APP_BASE_URL +
    "resources/using-simplereport/manage-facility-info/find-supported-jurisdictions/",
};

export const securityQuestions = [
  "What’s your first pet’s name?",
  "What’s your favorite book?",
  "What’s your favorite food?",
];

export const accountCreationSteps = [
  { label: "Create your password", value: "0", order: 0 },
  { label: "Select your security question", value: "1", order: 1 },
  { label: "Set up authentication", value: "2", order: 2 },
];
