package gov.cdc.usds.simplereport.api.model.useraccountcreation;

public enum UserAccountStatus {
  ACTIVE,
  PENDING_ACTIVATION,
  PASSWORD_RESET,
  SET_SECURITY_QUESTIONS,
  MFA_SELECT,
  SMS_PENDING_ACTIVATION,
  CALL_PENDING_ACTIVATION,
  EMAIL_PENDING_ACTIVATION,
  GOOGLE_PENDING_ACTIVATION,
  OKTA_PENDING_ACTIVATION,
  FIDO_PENDING_ACTIVATION,
  UNKNOWN
}
