name: Deploy SimpleReport Front End
description: Build and deploy the React application
inputs:
  deploy-env:
    description: The environment being deployed (e.g. "prod" or "test")
    required: true
  smarty-streets-key:
    description: The Smarty-Streets API token for this environment. (Should be fetched from vault but is not)
    required: true
  base-domain-name:
    description: The domain where the application is deployed (e.g. "simplereport.gov" or "test.simplereport.gov")
    required: false
  is-training-site:
    description: If this is set, special training branding will be applied.
    required: false
runs:
  using: composite
  steps:
    - name: Install dependencies
      working-directory: ./frontend
      shell: bash
      run: yarn install
    - name: Set build variables
      shell: bash
      working-directory: ./frontend
      run: |
          az config set extension.use_dynamic_install=yes_without_prompt > /dev/null 2>&1
          INSIGHTS_KEY=$(
            az monitor app-insights component show \
              -g prime-simple-report-${{inputs.deploy-env}} \
              -a prime-simple-report-${{inputs.deploy-env}}-insights \
            | jq -r '.instrumentationKey')
          echo "REACT_APP_APPINSIGHTS_KEY=${INSIGHTS_KEY}" > .env.production.local
          if [[ -n "${{ inputs.base-domain-name }}" ]]
            then echo "REACT_APP_BASE_URL=https://${{inputs.base-domain-name}}" >> .env.production.local
          fi
          if [[ "true" == "${{ inputs.is-training-site }}" ]]
            then echo "REACT_APP_IS_TRAINING_SITE=true" >> .env.production.local
          fi
    - name: Build deployable application
      shell: bash
      working-directory: ./frontend
      env:
        REACT_APP_SMARTY_STREETS_KEY: ${{ inputs.smarty-streets-key }}
        DEPLOY_ENV: ${{ inputs.deploy-env }}
      run: yarn run build
    - name: Deploy frontend app
      shell: bash
      working-directory: ./frontend
      run: |
        az storage blob upload-batch -s build/ -d '$web' \
          --account-name simplereport${{ inputs.deploy-env }}app \
          --destination-path '/app'
    - name: Purge CDN
      shell: bash
      working-directory: ./frontend
      run: |
        az cdn endpoint purge \
          --resource-group prime-simple-report-${{ inputs.deploy-env }} \
          --profile-name simple-report-${{ inputs.deploy-env }} \
          --name simple-report-${{ inputs.deploy-env }} \
          --content-paths "/app/*" --no-wait
