name: Build SimpleReport Front End
description: Build the React application
inputs:
  deploy-env:
    description: The environment being deployed (e.g. "prod" or "test")
    required: true
  smarty-streets-key:
    description: The Smarty-Streets API token for this environment. (Should be fetched from vault but is not)
    required: true
  base-domain-name:
    description: The domain where the application is deployed (e.g. "simplereport.gov" or "test.simplereport.gov")
    required: false
  client-tarball:
    description: The path to the tar file containing the client code to deploy
    required: true
  is-training-site:
    description: If this is set, special training branding will be applied.
    required: false
  okta-enabled:
    description: If this is set, the app will redirect to Okta if no one is logged in.
    required: true
  okta-url:
    description: The Okta instance to redirect to.
    required: false
  okta-client-id:
    description: The Okta client ID for this environment.
    required: false
runs:
  using: composite
  steps:
    - name: Install dependencies
      working-directory: ./frontend
      shell: bash
      run: |
        echo "::group::Install dependencies (hopefully cached)"
        yarn install
        echo "::endgroup::"
    - name: Set build variables
      shell: bash
      working-directory: ./frontend
      run: |
          echo "::group::Set build variables"
          ENVLVL=${{inputs.deploy-env}}
          ENVLVL=${ENVLVL//[[:digit:]]/}
          echo "Environment level: $ENVLVL"
          az config set extension.use_dynamic_install=yes_without_prompt
          INSIGHTS_CONNECTION_STRING=$(
            az monitor app-insights component show \
              -g prime-simple-report-$ENVLVL \
              -a prime-simple-report-${{inputs.deploy-env}}-insights \
            | jq -r '.connectionString')
          echo "VITE_APPLICATIONINSIGHTS_CONNECTION_STRING=${INSIGHTS_CONNECTION_STRING}" > .env.production.local
          if [[ -n "${{ inputs.base-domain-name }}" ]]
            then echo "VITE_BASE_URL=https://${{inputs.base-domain-name}}" >> .env.production.local
          fi
          if [[ "true" == "${{ inputs.is-training-site }}" ]]
            then echo "VITE_IS_TRAINING_SITE=true" >> .env.production.local
          fi
          if [[ "true" == "${{ inputs.okta-enabled }}" ]]; then 
            echo "VITE_OKTA_ENABLED=true" >> .env.production.local
            echo "VITE_OKTA_URL=${{inputs.okta-url}}" >> .env.production.local
            echo "VITE_OKTA_CLIENT_ID=${{inputs.okta-client-id}}" >> .env.production.local
          fi
          echo "::endgroup::"
    - name: Build deployable application
      shell: bash
      working-directory: ./frontend
      env:
        VITE_SMARTY_STREETS_KEY: ${{ inputs.smarty-streets-key }}
        DEPLOY_ENV: ${{ inputs.deploy-env }}
      run: |
        echo "::group::Build application"
        yarn run build
        echo "::endgroup::"
    - name: Create client build archive
      shell: bash
      run: |
        echo "::group::Create application archive"
        tar -C ./frontend/build -czf ${{inputs.client-tarball}} .
        echo "::endgroup::"
