simple-report:
  azure-reporting-queue:
    enabled: true
    fhir-queue-enabled: true
    exception-webhook-enabled: true
  patient-link-url: https://dev2.simplereport.gov/app/pxp?plid=
  twilio-callback-url: https://dev2.simplereport.gov/api/pxp/callback
  sendgrid:
    enabled: false
  cors:
    allowed-origins:
      - https://simplereportdev2app.z13.web.core.windows.net
      - https://simple-report-api-dev2.azurewebsites.net
      - https://simple-report-dev2.azureedge.net
      - https://dev2.simplereport.gov
twilio:
  enabled: true
features:
  oktaMigrationEnabled: true
