spring:
  profiles.include: okta-stg
simple-report:
  patient-link-url: https://stg.simplereport.gov/app/pxp?plid=
  twilio-callback-url: https://stg.simplereport.gov/api/pxp/callback
  cors:
    allowed-origins:
      - https://simple-report-api-stg.azurewebsites.net
      - https://simple-report-stg.azureedge.net
      - https://stg.simplereport.gov
  experian:
    enabled: true
