simple-report:
  data-retention:
    enabled: false
    retention-days: 30
    batch-size: 1000
    max-execution-time-minutes: 120
  patient-link-url: https://pentest.simplereport.gov/app/pxp?plid=
  twilio-callback-url: https://pentest.simplereport.gov/api/pxp/callback
  sendgrid:
    enabled: true
  cors:
    allowed-origins:
      - https://simple-report-api-pentest.azurewebsites.net
      - https://simple-report-pentest.azureedge.net
      - https://pentest.simplereport.gov
twilio:
  enabled: true
