simple-report:
  azure-reporting-queue:
    enabled: true
    fhir-queue-enabled: true
    exception-webhook-enabled: true
  processing-mode-code: T
  patient-link-url: https://stg.simplereport.gov/app/pxp?plid=
  twilio-callback-url: https://stg.simplereport.gov/api/pxp/callback
  cors:
    allowed-origins:
      - https://simple-report-api-stg.azurewebsites.net
      - https://simple-report-stg.azureedge.net
      - https://stg.simplereport.gov
  experian:
    enabled: true
