simple-report:
  azure-reporting-queue:
    enabled: true
    fhir-queue-enabled: true
    exception-webhook-enabled: true
  patient-link-url: https://dev4.simplereport.gov/app/pxp?plid=
  twilio-callback-url: https://dev4.simplereport.gov/api/pxp/callback
  sendgrid:
    enabled: false
  cors:
    allowed-origins:
      - https://simplereportdev4app.z13.web.core.windows.net
      - https://simple-report-api-dev4.azurewebsites.net
      - https://simple-report-dev4.azureedge.net
      - https://dev4.simplereport.gov
twilio:
  enabled: true