# Bean profile to be included in deployment-specific profiles
# for DEV/TEST deployments.
okta:
  oauth2:
    client-id: 0oa3ivrvd9Jhvt8Sb1d7
    issuer: https://hhs-prime.oktapreview.com/oauth2/default
  client:
    org-url: https://hhs-prime.oktapreview.com
simple-report:
  authorization:
    role-claim: dev_roles
    environment-name: "DEV3"
