spring:
  profiles.include: okta-dev3, server-debug
simple-report:
  azure-reporting-queue:
    enabled: true
    fhir-queue-enabled: true
    exception-webhook-enabled: true
  patient-link-url: https://dev3.simplereport.gov/app/pxp?plid=
  twilio-callback-url: https://dev3.simplereport.gov/api/pxp/callback
  sendgrid:
    enabled: false
  cors:
    allowed-origins:
      - https://simplereportdev3app.z13.web.core.windows.net
      - https://simple-report-api-dev3.azurewebsites.net
      - https://simple-report-dev3.azureedge.net
      - https://dev3.simplereport.gov
  fhir-reporting-enabled: false
twilio:
  enabled: true
