name: DB Liquibase Action
description: Runs Liquibase actions in a container

inputs:
  # Environment configuration
  deploy_env:
    description: The environment of the database.
    required: true

  # Docker Compose file configuration
  docker_compose_file:
    description: The docker compose file to use.
    default: docker-compose.db-liquibase-action.yml
    required: false

  # Liquibase action and git_sha tag value
  action:
    description: The git sha of the image to use.
    required: true

  # Liquibase rollback configuration
  liquibase_rollback_tag:
    description: Only required if rollback is selected. The Liquibase tag to roll back to
    required: false

  # Azure credentials configuration
  azure_credentials:
    description: Azure credentials
    required: true

  # ACR configuration
  acr_repo_url:
    description: ACR repo url
    required: true
  acr_admin_username:
    description: ACR admin username
    required: true
  acr_admin_pasword:
    description: ACR admin password
    required: true

  # Terraform ARM configuration
  terraform_arm_client_id:
    description: Terraform ARM client id
    required: true
  terraform_arm_client_secret:
    description: Terraform ARM client secret
    required: true
  terraform_arm_subscription_id:
    description: Terraform ARM subscription id
    required: true
  terraform_arm_tenant_id:
    description: Terraform ARM tenant id
    required: true

runs:
  using: composite
  steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Login to ACR
      shell: bash
      run: docker login ${{ inputs.acr_repo_url }} -u ${{ inputs.acr_admin_username }} -p ${{ inputs.acr_admin_pasword }}

    - name: Delete existing ${{ inputs.action }} image
      shell: bash
      run: |
        az acr repository delete \
          --name simplereportacr \
          --image api/simple-report-api-build:${{ inputs.action }} \
          --yes || echo "No ${{ inputs.action }} image to delete"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker images
      shell: bash
      working-directory: ./backend
      env:
        DOCKER_COMPOSE_FILE: ${{ inputs.docker_compose_file }}
        GIT_SHA: ${{ inputs.action }}
      run: ./build_and_push.sh
    
    - name: Terraform setup
      uses: hashicorp/setup-terraform@v3.1.1
      with:
        terraform_version: 1.9.5
    
    - name: Terraform init
      shell: bash
      working-directory: ./ops
      env:
        ARM_CLIENT_ID: ${{ inputs.terraform_arm_client_id }}
        ARM_CLIENT_SECRET: ${{ inputs.terraform_arm_client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.terraform_arm_subscription_id }}
        ARM_TENANT_ID: ${{ inputs.terraform_arm_tenant_id }}
      run: make init-${{ inputs.deploy_env }}

    - name: Terraform apply DB db_liquibase_action Container Instance
      shell: bash
      working-directory: ./ops
      env:
        ARM_CLIENT_ID: ${{ inputs.terraform_arm_client_id }}
        ARM_CLIENT_SECRET: ${{ inputs.terraform_arm_client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.terraform_arm_subscription_id }}
        ARM_TENANT_ID: ${{ inputs.terraform_arm_tenant_id }}
      run: |
        terraform -chdir=${{ inputs.deploy_env }} apply \
        -var acr_image_tag=dummy \
        -var liquibase_rollback_tag="${{ inputs.liquibase_rollback_tag }}" \
        -var image_action=${{ inputs.action }} \
        -target module.db_liquibase_action[0] --auto-approve

    - name: Display container logs
      if: always()
      shell: bash
      run: |
        RESOURCE_GROUP=${{ inputs.deploy_env }}
        if [[ "${{ inputs.deploy_env }}" == *dev* ]]; then RESOURCE_GROUP=dev; fi;
        echo "Resource Group: $RESOURCE_GROUP"
        az container logs --follow -g "prime-simple-report-$RESOURCE_GROUP" --name "simple-report-${{ inputs.deploy_env }}-db-${{ inputs.action }}"
        if [ "$(az container show -g "prime-simple-report-$RESOURCE_GROUP" --name "simple-report-${{ inputs.deploy_env }}-db-${{ inputs.action }}" | jq '.containers[].instanceView.currentState.exitCode')" != "null" ]; then
          exit $(az container show -g "prime-simple-report-$RESOURCE_GROUP" --name "simple-report-${{ inputs.deploy_env }}-db-${{ inputs.action }}" | jq '.containers[].instanceView.currentState.exitCode')
        else
          echo "No instance view available for the specified container group."
          exit 1
        fi;

    - name: Terraform destroy DB db_liquibase_action Container Instance
      if: always()
      shell: bash
      working-directory: ./ops
      env:
        ARM_CLIENT_ID: ${{ inputs.terraform_arm_client_id }}
        ARM_CLIENT_SECRET: ${{ inputs.terraform_arm_client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.terraform_arm_subscription_id }}
        ARM_TENANT_ID: ${{ inputs.terraform_arm_tenant_id }}
      run: |
        terraform -chdir=${{ inputs.deploy_env }} destroy \
        -var acr_image_tag=dummy \
        -var liquibase_rollback_tag="" \
        -var image_action=${{ inputs.action }} \
        -target module.db_liquibase_action[0] --auto-approve
