name: Build and Push
description: Build and push Docker image to the registry
inputs:
  acr_registry:
    description: Azure Container Registry to push the image to
    required: true
  acr_username:
    description: Azure Container Registry username
    required: true
  acr_password:
    description: Azure Container Registry password
    required: true

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to ACR
      shell: bash
      run: docker login ${{ inputs.acr_registry }} -u ${{ inputs.acr_username }} -p ${{ inputs.acr_password }}
    - name: Build and push Backend image
      working-directory: ./backend
      shell: bash
      run: ./build_and_push.sh
    - name: Build and push db client image
      working-directory: ./ops/services/container_instances/db_client/image
      shell: bash
      run: ./build_and_push.sh
