name: Terraform Action wait for slot readiness
description: Build and push Docker image to the registry
inputs:
  deploy_env:
    description: The environment to deploy to
    required: true

runs:
  using: composite
  steps:
    - name: Wait for staging deploy to be ready
      working-directory: ./ops
      shell: bash
      run: make wait-for-${{ inputs.deploy_env }}-slot-readiness
