name: Build frontend docker image

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      force_build:
        description: Force build
        required: false
        default: false
        type: boolean
    outputs:
      version:
        description: docker image version
        value: ${{ jobs.build_and_push_frontend_image.outputs.version }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend

jobs:

  frontend_changes:
    with:
      what_to_check: frontend
    uses: ./.github/workflows/checkForChanges.yml

  build_and_push_frontend_image:
    # We want to build the image if there are changes in the frontend folder, or if we are forcing a build, or if we are on the main branch
    if: needs.frontend_changes.outputs.has_changes == 'true' || inputs.force_build == true || github.ref == 'refs/heads/main'
    needs: [frontend_changes]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.set.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "REACT_APP_OKTA_URL=http://wiremock:8088"
            "REACT_APP_OKTA_CLIENT_ID=0oa1k0163nAwfVxNW1d7"
            "REACT_APP_BASE_URL=https://localhost.simplereport.gov"
            "REACT_APP_BACKEND_URL=https://localhost.simplereport.gov/api"
            "PUBLIC_URL=/app/"
            "REACT_APP_OKTA_ENABLED=true"
            "REACT_APP_DISABLE_MAINTENANCE_BANNER=true"

      - name: Set version output
        shell: bash
        id: set
        run: echo "version=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}" >> "$GITHUB_OUTPUT"
