name: Build Docker Images

on:
  workflow_dispatch:

jobs:

  build_cypress_image:
    uses: ./.github/workflows/buildCypressImage.yml

  build_database_image:
    uses: ./.github/workflows/buildDatabaseImage.yml
