name: Build cypress docker image

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/cypress

jobs:

  cypress_changes:
    with:
      what_to_check: cypress
    uses: ./.github/workflows/checkForChanges.yml

  build-and-push-cypress-image:
    needs: [cypress_changes]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        if: needs.cypress_changes.outputs.has_changes == 'true'
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        if: needs.cypress_changes.outputs.has_changes == 'true'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: needs.cypress_changes.outputs.has_changes == 'true'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=branch

      - name: Build and push Docker image
        if: needs.cypress_changes.outputs.has_changes == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./cypress/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Skip build
        if: needs.cypress_changes.outputs.has_changes == 'false'
        run: echo "No changes in cypress directory, skipping build"
