name: Check Graphql Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

env:
  NODE_VERSION: 14

defaults:
  run:
    working-directory: frontend

jobs:
  check-graphql-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Cache npm local files
        uses: actions/cache@v2
        with:
          path: |
            ./frontend/node_modules
          key: npm-${{env.NODE_VERSION}}-${{ hashFiles('frontend/yarn.lock', 'frontend/package.json') }}
      - name: Node setup
        run: yarn
      - name: Generate grahpql types
        run: yarn codegen
      - name: Lint generated files
        run: yarn lint:write
      - name: Check for changes
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "Current generated code does not match code in latest commit. try running `cd frontend/ && yarn codegen`"
            git diff >> diff.txt
            exit 1
          fi
      - name: Archive git diff
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report
          path: backend/build/reports/tests/test
          retention-days: 7