name: Chromatic

on:
  workflow_dispatch:
  push:
    paths:
      - "frontend/**"

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Chromatic wants the history
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn
        working-directory: frontend
      - name: Publish to Chromatic
        if: github.ref != 'refs/heads/main'
        uses: chromaui/action@v1
        with:
          workingDir: frontend
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          ignoreLastBuildOnBranch: "**"  # Better comparisons after rebasing
          exitZeroOnChanges: true
          exitOnceUploaded: true
      - name: Publish to Chromatic (auto-accept changes on merge main)
        if: github.ref == 'refs/heads/main'
        uses: chromaui/action@v1
        with:
          workingDir: frontend
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          ignoreLastBuildOnBranch: "**"
          exitZeroOnChanges: true
          exitOnceUploaded: true
          autoAcceptChanges: true  # handle squash-on-merge
