      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Terraform Plan Output

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Terraform Plan Output**

            ```diff
            ${{ steps.plan.outputs.tfplan_persistent }}
            ${{ steps.plan.outputs.tfplan }}
            ```

      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            **Terraform Plan Output**

            ```diff
            ${{ steps.plan.outputs.tfplan_persistent }}
            ${{ steps.plan.outputs.tfplan }}
            ```