name: Run end-to-end tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  # workflow_run:
  #   workflows: 
  #     - Build Docker Images
  #   types:
  #     - completed

jobs:

  cypress_changes:
    with:
      what_to_check: cypress
    uses: ./.github/workflows/checkForChanges.yml

  database_changes:
    with:
      what_to_check: backend/db-setup
    uses: ./.github/workflows/checkForChanges.yml

  cypress_tag:
    needs: [cypress_changes]
    if: needs.cypress_changes.outputs.has_changes == 'true'
    uses: ./.github/workflows/getDockerBranchTag.yml

  database_tag:
    needs: [database_changes]
    if: needs.database_changes.outputs.has_changes == 'true'
    uses: ./.github/workflows/getDockerBranchTag.yml

  cypress-local-env:
    if: always()
    needs: [cypress_tag, database_tag]
    runs-on: ubuntu-latest
    steps:
            
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Swap Space
      uses: ./.github/actions/set-swap-space
      with:
        swap-size-gb: 10

    - name: Generate certs
      run: |
        echo "::group::Generate ssl certs"
        sudo apt install libnss3-tools
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install mkcert
        mkcert -install
        mkdir -p certs
        cd certs
        mkcert localhost.simplereport.gov
        mv localhost.simplereport.gov.pem localhost.simplereport.gov.crt
        mv localhost.simplereport.gov-key.pem localhost.simplereport.gov.key
        cd ..
        echo "::endgroup::"

    - name: Update files permissions
      # Even though we don't use it, we need the .env file created here due to an issue similar to this one: https://github.com/mutagen-io/mutagen/issues/265
      run: |
        echo "::group::Update permissions"
        echo FAKE_ENV="true" >> .env
        sudo chmod -R 777 backend
        sudo chmod -R 777 frontend
        echo "::endgroup::"

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Cypress
      timeout-minutes: 30
      env:
        # CI settings
        CI: 1
        # docker settings
        DOCKER_CLIENT_TIMEOUT: 180
        # DOCKER_CYPRESS_IMAGE_TAG: ${{ needs.cypress_tag.outputs.tag }}
        # DOCKER_DATABASE_IMAGE_TAG: ${{ needs.database_tag.outputs.tag }}
        COMPOSE_HTTP_TIMEOUT: 180
        # backend settings
        SPRING_PROFILES_ACTIVE: e2e,db-dockerized
        OKTA_TESTING_DISABLEHTTPSCHECK: "true"
        OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}
        OKTA_OAUTH2_CLIENT_ID: 0oa1k0163nAwfVxNW1d7
        SMARTY_AUTH_ID: ${{ secrets.SMARTY_AUTH_ID }}
        SMARTY_AUTH_TOKEN: ${{ secrets.SMARTY_AUTH_TOKEN }}
        SPRING_LIQUIBASE_ENABLED: "true"
        GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
        # cypress settings
        CYPRESS_OKTA_USERNAME: ${{ secrets.CYPRESS_OKTA_USERNAME }}
        CYPRESS_OKTA_PASSWORD: ${{ secrets.CYPRESS_OKTA_PASSWORD }}
        CYPRESS_OKTA_SECRET: ${{ secrets.CYPRESS_OKTA_SECRET }}
        CYPRESS_BACKEND_URL: "https://localhost.simplereport.gov/api"
        WIREMOCK_URL: "http://cypress:8088"
        SPEC_PATH: "cypress/integration/*"
        TEST_ENV: "https://localhost.simplereport.gov"
        # frontend settings
        REACT_APP_OKTA_URL: "http://cypress:8088"
        REACT_APP_OKTA_CLIENT_ID: 0oa1k0163nAwfVxNW1d7
        REACT_APP_BASE_URL: https://localhost.simplereport.gov
        REACT_APP_BACKEND_URL: https://localhost.simplereport.gov/api
        PUBLIC_URL: /app/
        REACT_APP_OKTA_ENABLED: "true"
        REACT_APP_DISABLE_MAINTENANCE_BANNER: "true"
      shell: bash
      run: |
        echo "::group::Run Cypress locally"
        docker compose pull
        docker compose -f docker-compose.yml -f docker-compose.cypress.yml build
        docker compose -f docker-compose.yml -f docker-compose.cypress.yml up --abort-on-container-exit --attach cypress --exit-code-from cypress
        echo "::endgroup::"
        
      # echo "Cypress branch tag (or latest): ${{ needs.set_docker_branch_image_tag.outputs.docker_cypress_image_tag }}"
      # docker compose -f docker-compose.yml -f docker-compose.cypress.yml up --abort-on-container-exit --attach cypress --exit-code-from cypress
      # echo "::endgroup::"

    - name: Get docker logs
      if: always()
      shell: bash
      run: |
        CONTAINERS=$(docker ps -a --format '{{.Names}}')
        for container in $CONTAINERS
        do
          echo "Saving $container logs"
          docker logs $container >& cypress/${container}.log
        done

    - name: Stop containers
      if: always()
      shell: bash
      run: |
        echo "::group::Stop Docker containers"
        docker compose -f docker-compose.yml -f docker-compose.cypress.yml down
        echo "::endgroup::"

    - name: Archive cypress failures
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-results
        path: |
          cypress/videos/*
          cypress/screenshots/*

    - name: Archive docker logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: cypress/*.log
