name: Delete old container images


on:
  schedule:
    - cron: "0 0 1 * *"

permissions:
  packages: write

jobs:
  clean_ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete all containers older than a month
        uses: snok/container-retention-policy@v2
        with:
          image-names: nginx, backend, frontend, cypress, frontend-lighthouse, database
          cut-off: One month ago UTC
          account-type: org
          org-name: CDCgov
          keep-at-least: 1
          skip-tags: main
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
