name: Delete old container images

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  clean_ghcr:
    name: Delete untagged container images
    runs-on: ubuntu-latest
    steps:
      # backend, cypress, database, frontend, frontend-lighthouse, nginx
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'backend'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'cypress'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'database'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'frontend'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'frontend-lighthouse'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'nginx'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'
