name: Replace Keys
run-name: Replace keys for ${{ inputs.deploy_env }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'The environment to deploy to'
        required: true
        type: choice
        options:
          - ""
          - dev
          - dev2
          - dev3
          - dev4
          - dev5
          - dev6
          - pentest
          - demo
          - test
          - training
          - stg
          - prod
          - all_environments
      replace_keys:
        description: 'Replace keys'
        default: "false"
        type: string
env:
  NODE_VERSION: 18

concurrency:
  group: ${{ github.event.inputs.deploy_env }}-deploy
  cancel-in-progress: false

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
    - id: set_matrix
      uses: ./.github/actions/matrix-prep
      with:
        env: ${{ inputs.deploy_env }}
  echo_matrix:
    runs-on: ubuntu-latest
    needs: matrix_prep
    steps:
    - run: echo ${{ needs.matrix_prep.outputs.matrix }}
