name: Rollback Pentest API

on:
  workflow_dispatch:

env:
  DEPLOY_ENV: pentest
concurrency:
  group: pentest-deploy

jobs:
  rollback:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ops
    env: # all Azure interaction is through terraform
      ARM_CLIENT_ID: ${{ secrets.TERRAFORM_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TERRAFORM_ARM_TENANT_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Roll back to previous release
        uses: ./.github/actions/rollback-application
        with:
          deploy-env: ${{env.DEPLOY_ENV}}
