name: Smoke test deploy Dev
run-name: Smoke test the deploy for dev by @${{ github.actor }}

on:
  workflow_run:
    workflows: [ "Deploy Dev" ]
    types:
      - completed
    branches:
      - "mike/7160-post-deploy-alert**"

env:
  NODE_VERSION: 20

jobs:
  smoke-test-front-and-back-end:
    runs-on: ubuntu-latest
    environment: dev5
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Cache yarn
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Set up dependencies
        working-directory: frontend
        run: yarn install --prefer-offline
      - name: Smoke test the env
        uses: ./.github/actions/post-deploy-smoke-test
        with:
          base_domain_name: dev5.simplereport.gov
  slack_alert:
    runs-on: ubuntu-latest
    if: failure()
    needs: [ smoke-test-front-and-back-end ]
    steps:
      - uses: actions/checkout@v4
      - name: Send alert to Slack
        uses: ./.github/actions/slack-message
        with:
          username: ${{ github.actor }}
          description: |
            :construction: Dev testing to confirm post-deploy smoke test works correctly. ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} :construction:
          webhook_url: ${{ secrets.SR_ALERTS_SLACK_WEBHOOK_URL }}
          user_map: $${{ secrets.SR_ALERTS_GITHUB_SLACK_MAP }}