name: Smoke test deploy
run-name: Smoke test the deploy for a dev env by @${{ github.actor }}

on:
  #  DELETE ME WHEN MERGING
  push:
  #  UNCOMMENT ME WHEN MERGING
#  workflow_dispatch:
#    inputs:
#      deploy_env:
#        description: 'The environment to smoke test'
#        required: true
#        type: choice
#        options:
#          - ""
#          - dev
#          - dev2
#          - dev3
#          - dev4
#          - dev5
#          - dev6
#          - dev7
#          - pentest

env:
  NODE_VERSION: 18

jobs:
  smoke-test-front-and-back-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache yarn
        uses: actions/cache@v3.3.2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Set up dependencies
        working-directory: frontend
        run: yarn install --prefer-offline
      - name: Smoke test the env
        uses: ./.github/actions/post-deploy-smoke-test
        with:
          #        REPLACE ME WITH deploy-env: ${{inputs.deploy_env}}
          deploy-env: dev7

