name: Test Liquibase rollbacks

# Run this on pushes to any branch that changes a Liquibase changelog
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
    paths:
      - backend/src/main/resources/db/changelog/db.changelog-master.yaml

defaults:
  run:
    working-directory: backend

jobs:
  test-db-rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start DB
        run: touch ../.env && docker compose -f ../docker-compose.yml up -d db
      - name: Build rollback image
        run: docker compose -f docker-compose.db-rollback.yml build
      - name: Run forward migrations
        run: docker compose -f docker-compose.db-rollback.yml run --entrypoint "gradle liquibaseUpdate" rollback
      - name: Test rolling back on last 20 migrations
        run: docker compose -f docker-compose.db-rollback.yml run --env LIQUIBASE_ROLLBACK_COUNT=20 rollback
