# Use this action if we want these alerts to show up in the Github Security Alerts: https://github.com/marketplace/actions/run-tfsec-with-sarif-upload
# Use this action if we want these alerts to be added as comments on a PR: https://github.com/marketplace/actions/run-tfsec-with-sarif-upload
# This action repo: https://github.com/aquasecurity/tfsec-action
name: tfsec

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          # added these exceptions for now, the ticket to fix them is here: https://github.com/CDCgov/prime-simplereport/issues/5879
          additional_args: -e azure-keyvault-ensure-key-expiry,azure-keyvault-no-purge
