name: Update keys and deploy Dev*

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  packages: write

jobs:
  key_rotation:
    strategy:
      fail-fast: false
      matrix:
        include:
          - deploy_env: dev
          # - deploy_env: dev2
          # - deploy_env: dev3
          # - deploy_env: dev4
          # - deploy_env: dev5
          # - deploy_env: dev6
          # - deploy_env: dev7
          # - deploy_env: pentest
    with:
      deploy_env: ${{ matrix.deploy_env }}
      replace_keys: "true"
    uses: ./.github/workflows/deployDev.yml
    secrets: inherit

  # update_keys_and_deploy_prod:
  #   if: never()
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - deploy_env: test
  #         - deploy_env: demo
  #         - deploy_env: training
  #         - deploy_env: stg
  #         - deploy_env: prod
  #   with:
  #     deploy_env: ${{ matrix.deploy_env }}
  #     replace_keys: "true"
  #   uses: ./.github/workflows/deployDev.yml
  #   secrets: inherit
