name: Build test data publisher functions
description: Build functions for test data publisher function app
inputs:
  deploy-env:
    description: The environment being deployed (e.g. "prod" or "test")
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Build function source bundle
      shell: bash
      working-directory: ./ops/services/app_functions/test_data_publisher/functions
      run: |
        echo "::group::Build function"
        yarn build:production
