name: Build test data publisher functions
description: Build local package file for functions in test data publisher function app
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Build function source bundle
      shell: bash
      working-directory: ./ops/services/app_functions/test_data_publisher/functions
      run: |
        echo "Build function"
        yarn build:production
